### ISSUE TITLE
拉取最新源码后bot报错，无法启动

### ISSUE THREAD

**Issue by Nigel-NI** [Arondight/Adachi-BOT#165]
按更新步骤更新后，bot无法启动（尽管npm处显示online）。错误代码如下：
```
0|bot      | }
0|bot      | TypeError: (master || []) is not iterable
0|bot      |     at readSettingAndGreeting (file:///root/Adachi-BOT/src/utils/config.js:196:48)
0|bot      |     at readConfig (file:///root/Adachi-BOT/src/utils/config.js:269:3)
0|bot      |     at main (file:///root/Adachi-BOT/app.js:102:9)
0|bot      |     at file:///root/Adachi-BOT/app.js:109:7
0|bot      |     at ModuleJob.run (internal/modules/esm/module_job.js:169:25)
0|bot      |     at async Loader.import (internal/modules/esm/loader.js:177:24)
0|bot      | TypeError: (master || []) is not iterable
0|bot      |     at readSettingAndGreeting (file:///root/Adachi-BOT/src/utils/config.js:196:48)
0|bot      |     at readConfig (file:///root/Adachi-BOT/src/utils/config.js:269:3)
0|bot      |     at main (file:///root/Adachi-BOT/app.js:102:9)
0|bot      |     at file:///root/Adachi-BOT/app.js:109:7
0|bot      |     at ModuleJob.run (internal/modules/esm/module_job.js:169:25)
0|bot      |     at async Loader.import (internal/modules/esm/loader.js:177:24)
```

**Comment by Mark9804** [comment]
> TypeError: (master || []) is not iterable
检查一下你的`setting.yml`里面，`masters`（即bot管理员）的配置是正确的吗？至少需要配置一个账号作为管理员账号

**Comment by Nigel-NI** [comment]
将原先的master改成masters后即恢复正常，感谢开发大大回复！

**Comment by Arondight** [comment]
昨天改错代码了，这俩应该是写哪个都行的，甚至你可以同时用

**Comment by Arondight** [comment]
```
# 管理者 QQ，一个或多个
masters:
  - 22222222
  - 11111111
# 此选项已弃用，但仍生效，建议使用 masters
master: 987654321
```

```
配置：管理者已设置为 22222222 、 11111111 、 987654321 。
```
