### ISSUE TITLE
响应消息的命令似乎得不到bot的回复

### ISSUE THREAD

**Issue by liyu30** [Arondight/Adachi-BOT#216]
响应消息的命令得不到BOT的回复，但是命令却是执行了的，数据库里面能看到状态发生改变。
```
[32m[2021-10-13T10:50:45.923] [INFO] [iPad:19****390] - [39mrecv from: [Private: 13****671(friend)] 响应消息 82****713 off
[91m[2021-10-13T10:50:45.926] [ERROR] [iPad:19****390] - [39mTypeError: Cannot read properties of undefined (reading 'sendMessage')
    at response (file:///www/wwwroot/Adachi-BOT/src/plugins/master/index.js:12:13)
    at setReplyAuth (file:///www/wwwroot/Adachi-BOT/src/plugins/master/index.js:107:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Plugin (file:///www/wwwroot/Adachi-BOT/src/plugins/master/index.js:161:7)
    at async Module.Wrapper (file:///www/wwwroot/Adachi-BOT/src/plugins/master/index.js:171:5)
```

**Comment by Mark9804** [comment]
确实不响应了，能够复现
