### ISSUE TITLE
在禁用了群的游戏数据权限之后，使用米游社来查询信息时会报错，但是不影响使用

### ISSUE THREAD

**Issue by FengLing11** [Arondight/Adachi-BOT#245]
TypeError: Cannot read properties of undefined (reading 'sendMessage')
    at sendPrompt (file:///E:/Adachi-BOT/Adachi-BOT/src/utils/auth.js:4:13)
    at Plugin (file:///E:/Adachi-BOT/Adachi-BOT/src/plugins/card/index.js:28:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Module.Wrapper (file:///E:/Adachi-BOT/Adachi-BOT/src/plugins/card/index.js:67:5)

具体是这个
我用的系统是 Windows 11

**Comment by Arondight** [comment]
改完了，最迟明天推上来
