### ISSUE TITLE
服务器繁忙，需要设定什么吗

### ISSUE THREAD

**Issue by davidelectricfree** [Arondight/Adachi-BOT#342]
[2021-11-04T11:28:14.193] [ERROR] [Watch:811055003] - 服务器繁忙(register)
[2021-11-04T11:28:14.193] [MARK] [Watch:811055003] - 5秒后重新连接。
[2021-11-04T11:28:14.193] [MARK] [Watch:811055003] - 109.244.129.248:8080 closed
[2021-11-04T11:28:19.212] [MARK] [Watch:811055003] - 正在探索可用服务器...
[2021-11-04T11:28:19.212] [DEBUG] [Watch:811055003] - getMsg发生错误。
[2021-11-04T11:28:19.212] [DEBUG] [Watch:811055003] - TimeoutError: package timeout
    at Object.<anonymous> (C:\Adachi-BOT\node_modules\oicq\lib\client-ext.js:23:23)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\Adachi-BOT\node_modules\oicq\lib\client.js:594:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

**Comment by Mark9804** [comment]
我偶尔会遇到，是通过重启bot解决的

**Comment by davidelectricfree** [comment]
> 
> 
> 我偶尔会遇到，是通过重启bot解决的

它会自动重启似乎，我不知道把响应时间从1改为3有没有效果

**Comment by Arondight** [comment]
配置文件中没有任何能影响这个问题的选项，当前我们什么都做不了
