### ISSUE TITLE
重复查询时，数据无法返回

### ISSUE THREAD

**Issue by Xm798** [Arondight/Adachi-BOT#35]
![image](https://user-images.githubusercontent.com/48074861/129542099-b387eaee-d16c-48b3-b774-5137a43b8b56.png)
```
0|bot  | [2021-08-16T17:26:14.798] [INFO] [iPad:178186691] - 用户 1xxxxxxx6 在一小时内进行过查询操作，将返回上次数据
0|bot  | TimeoutError: Navigation timeout of 30000 ms exceeded
0|bot  |     at /home/yakult/Adachi-BOT/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
0|bot  | TimeoutError: Navigation timeout of 30000 ms exceeded
0|bot  |     at /home/yakult/Adachi-BOT/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
0|bot  | TimeoutError: Navigation timeout of 30000 ms exceeded
0|bot  |     at /home/yakult/Adachi-BOT/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
```

**Comment by Arondight** [comment]
机器内存多大的，chromium 死掉了

**Comment by Arondight** [comment]
我下班了，如果你是内存较小的 SSD VPS，可以考虑挂载一个 swap 文件，临时顶替一下内存，也能用。

**Comment by Xm798** [comment]
啊！原来如此，我是Synology拉的虚拟机，内存给到2G就好了。

**Comment by Xm798** [comment]
另外有个新的问题，回复 角色 和 武器 都会提示`查询失败，请检查名称是否正确`，是什么原因呢

**Comment by Arondight** [comment]
> 
> 
> 另外有个新的问题，回复 角色 和 武器 都会提示`查询失败，请检查名称是否正确`，是什么原因呢

首先检查一下命令是否使用正确。

```
角色 菲谢尔
武器 幽夜华尔兹
```

其次检查[本地文件服务](https://github.com/Arondight/Adachi-BOT#%E5%AE%89%E5%85%A8%E9%97%AE%E9%A2%98)是否正常。

```
wget -O - 'http://localhost:9934/resources/Version2/info/docs/菲谢尔.json'
```

**Comment by Xm798** [comment]
貌似定位到问题了，配置过程中使用`npm_config_proxy`配置了代理服务器，然后查询指令被发送到代理服务器了。
![image](https://user-images.githubusercontent.com/48074861/129552287-24fb6556-9533-48da-b17e-14eb7c625fab.png)
但我不太清楚如何取消代理，`npm config delete proxy`没有起作用。
bash中通过wget在没有代理的情况下可以正常获取文件。

**Comment by Arondight** [comment]
> 貌似定位到问题了，配置过程中使用`npm_config_proxy`配置了代理服务器，然后查询指令被发送到代理服务器了。
> ![image](https://user-images.githubusercontent.com/48074861/129552287-24fb6556-9533-48da-b17e-14eb7c625fab.png)
> 但我不太清楚如何取消代理，`npm config delete proxy`没有起作用。
> bash中通过wget在没有代理的情况下可以正常获取文件。

我明天试一下，我都是怕麻烦直接用的系统软件源中的 Chromium。你如果找到解决方法有空可以回一下，这确实也是个问题。

**Comment by Xm798** [comment]
> > 貌似定位到问题了，配置过程中使用`npm_config_proxy`配置了代理服务器，然后查询指令被发送到代理服务器了。
> > ![image](https://user-images.githubusercontent.com/48074861/129552287-24fb6556-9533-48da-b17e-14eb7c625fab.png)
> > 但我不太清楚如何取消代理，`npm config delete proxy`没有起作用。
> > bash中通过wget在没有代理的情况下可以正常获取文件。
> 
> 我明天试一下，我都是怕麻烦直接用的系统软件源中的 Chromium。你如果找到解决方法有空可以回一下，这确实也是个问题。

不太熟悉nodejs，没搞明白怎么取消之前设置的代理orz，重新用系统源的 Chromium 配置了一下。

**Comment by Arondight** [comment]
(⊙o⊙)… 最近忙的晕头转向，工作还不顺利，这个问题完全被我忘掉了……

**Comment by 490720818** [comment]
> 啊！原来如此，我是Synology拉的虚拟机，内存给到2G就好了。

群晖虚拟化效率太低了，我挂win server上内存占用才100MB

**Comment by Luomeng0104** [comment]
发uid+数字命令    机器人回复绘图失败如何解决

**Comment by Luomeng0104** [comment]
发uid+数字命令 机器人回复失败如何解决
代码框显示
错误： genshin-card 功能绘图失败，因为“Error: Node has 0 height.”

**Comment by Luomeng0104** [comment]
发uid加数字 ，器人回复绘图失败
代码框  显示： genshini-card 绘图功能失败，“Node has 0 height.”

**Comment by Arondight** [comment]
@Luomeng0104 麻烦新开一个 issue 按照模板填写一下信息吧，我也不知道这是为什么，至少得能复现才能排查

**Comment by Mark9804** [comment]
@Luomeng0104 麻烦新开一个 issue ，说明一下错误信息，**并且把** `你的bot根目录/data/record/last_params/genshin-card.json` **这个文件的内容贴出来**。这个错误信息代表你获取的数据当中出现了前端没有预期到的结构，我们必须有这个数据才能知道哪里出了问题

**Comment by Luomeng0104** [comment]
发了  大佬看看

**Comment by Luomeng0104** [comment]
@Mark9804 发了 大佬看看

**Comment by gaqwe767** [comment]
![QQ截图20230601211020](https://github.com/Arondight/Adachi-BOT/assets/64371245/11f8b9bd-e6ef-4258-bcca-6c794322e190)
最近我发现还会绘图失败的，获取深渊信息的时候。
