### ISSUE TITLE
npm run init时报错

### ISSUE THREAD

**Issue by Scp-Joker** [Arondight/Adachi-BOT#419]
### 问题描述

[2021-11-22T16:06:59.090] [WARN] - [下线通知]该帐号密码目前已经泄露，请按照系统指引重新登录，为避免产生损失建议及时修改密码。你也可以对帐号进行<TITLE="资金管理",URL="https://myun.tenpay.com/mqq/banneduser/index.shtml?_wv=1027">。
[2021-11-22T16:06:59.091] [MARK] - 193.112.231.60:8080 closed
[2021-11-22T16:07:04.023] [DEBUG] - getMsg发生错误。
[2021-11-22T16:07:04.023] [DEBUG] - TimeoutError: package timeout
    at Object.<anonymous> (/usr/local/Adachi-BOT/Adachi-BOT/node_modules/oicq/lib/client-ext.js:23:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/Adachi-BOT/Adachi-BOT/node_modules/oicq/lib/client.js:594:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

### 复现流程

npm run init时报错

### 代码状态：当前提交

.

### 运行环境：操作系统

Linux

**Comment by Arondight** [comment]
1. 确认下你读取的 QQ 是自己配置的还是默认的 987654321
2. 确认你使用的 QQ 是否正常
