### ISSUE TITLE
又崩溃了（

### ISSUE THREAD

**Issue by uyaddayu** [Arondight/Adachi-BOT#449]
### 问题描述

```
[2021-11-29T00:01:00.021] [DEBUG] [iPad:162273390] - 清理：删除数据库 aby 中 0 条无用记录。
[2021-11-29T00:01:00.021] [DEBUG] [iPad:162273390] - 清理：删除数据库 cookies 中 2 条无用记录。
[2021-11-29T00:01:00.021] [DEBUG] [iPad:162273390] - 清理：删除数据库 cookies_invalid 中 0 条无用记录。
[2021-11-29T00:01:00.027] [DEBUG] [iPad:162273390] - 清理：删除数据库 info 中 0 条无用记录。
file:///home/uyad/bot/Adachi-BOT/node_modules/node-fetch/src/index.js:95
			reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error));
			       ^

FetchError: request to https://webstatic.mihoyo.com/hk4e/gacha_info/cn_gf01/gacha/list.json failed, reason: getaddrinfo ENOTFOUND webstatic.mihoyo.com
    at ClientRequest.<anonymous> (file:///home/uyad/bot/Adachi-BOT/node_modules/node-fetch/src/index.js:95:11)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Job instance at:
    at /home/uyad/bot/Adachi-BOT/node_modules/node-schedule/lib/Invocation.js:273:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  erroredSysCall: 'getaddrinfo'
}

Node.js v17.1.0
```

### 复现流程

就0点自己奔溃了

### 代码状态：当前提交

-

### 运行环境：操作系统

Linux

**Comment by Arondight** [comment]
感谢老大哥帮忙测出来一堆 fetch 异常未处理的 bug ，不过话说回来你的 vps 连接米游社似乎有点小问题， hot 跑了小半年了你是第一个测出来这个问题的
