### ISSUE TITLE
启动源码时提示 MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by Nigel-NI** [Arondight/Adachi-BOT#458]
### 问题描述

使用`npm run start` 启动时报错，bot无法运行。错误代码请参考“后台日志”部分

### 复现流程

利用`git clone https://hub.fastgit.org/Arondight/Adachi-BOT.git`拉取源码，配置settings和cookies后，使用`npm run init`初始化，未见异常；使用`npm run start`启动，出现报错，无法启动

### 后台日志

```Text
# npm run start

> Adachi-BOT@1.5.0 start
> cross-env-shell PM2_HOME=$INIT_CWD/bot.pm2/ npx pm2 start ./.pm2.json; cross-env-shell PM2_HOME=$INIT_CWD/bot.pm2/ npx pm2 save

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@pm2/pm2-version-check'
Require stack:
- /root/Adachi-BOT/node_modules/pm2/lib/VersionCheck.js
- /root/Adachi-BOT/node_modules/pm2/lib/Client.js
- /root/Adachi-BOT/node_modules/pm2/lib/API.js
- /root/Adachi-BOT/node_modules/pm2/lib/binaries/CLI.js
- /root/Adachi-BOT/node_modules/pm2/bin/pm2
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/Adachi-BOT/node_modules/pm2/lib/VersionCheck.js:2:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/Adachi-BOT/node_modules/pm2/lib/VersionCheck.js',
    '/root/Adachi-BOT/node_modules/pm2/lib/Client.js',
    '/root/Adachi-BOT/node_modules/pm2/lib/API.js',
    '/root/Adachi-BOT/node_modules/pm2/lib/binaries/CLI.js',
    '/root/Adachi-BOT/node_modules/pm2/bin/pm2'
  ]
}
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@pm2/pm2-version-check'
Require stack:
- /root/Adachi-BOT/node_modules/pm2/lib/VersionCheck.js
- /root/Adachi-BOT/node_modules/pm2/lib/Client.js
- /root/Adachi-BOT/node_modules/pm2/lib/API.js
- /root/Adachi-BOT/node_modules/pm2/lib/binaries/CLI.js
- /root/Adachi-BOT/node_modules/pm2/bin/pm2
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/Adachi-BOT/node_modules/pm2/lib/VersionCheck.js:2:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/Adachi-BOT/node_modules/pm2/lib/VersionCheck.js',
    '/root/Adachi-BOT/node_modules/pm2/lib/Client.js',
    '/root/Adachi-BOT/node_modules/pm2/lib/API.js',
    '/root/Adachi-BOT/node_modules/pm2/lib/binaries/CLI.js',
    '/root/Adachi-BOT/node_modules/pm2/bin/pm2'
  ]
}

```
```


### 代码状态：当前提交

0eeeb16b23b03b7f4bb974cbf7da700f4ae6444d (HEAD -> master, origin/master, origin/dev, origin/HEAD) 增加荒泷一斗别名“一斗”

### 代码状态：是否修改

_No response_

### 运行环境： Node.js 版本

_No response_

### 运行环境： npm 版本

_No response_

### 运行环境：操作系统

Linux

**Comment by Arondight** [comment]
有执行 `npm install` 吗

**Comment by Mark9804** [comment]
`npm install`

**Comment by Nigel-NI** [comment]
已经执行过了，但是还是失败，报错代码还是一样
```

root@aaa:~/Adachi-BOT# npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 

up to date, audited 411 packages in 3m

39 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
root@aaa:~/Adachi-BOT# npm run start

> Adachi-BOT@1.5.0 start
> cross-env-shell PM2_HOME=$INIT_CWD/bot.pm2/ npx pm2 start ./.pm2.json; cross-env-shell PM2_HOME=$INIT_CWD/bot.pm2/ npx pm2 save

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@pm2/pm2-version-check'
Require stack:
- /root/Adachi-BOT/node_modules/pm2/lib/VersionCheck.js
- /root/Adachi-BOT/node_modules/pm2/lib/Client.js
- /root/Adachi-BOT/node_modules/pm2/lib/API.js
- /root/Adachi-BOT/node_modules/pm2/lib/binaries/CLI.js
- /root/Adachi-BOT/node_modules/pm2/bin/pm2
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/Adachi-BOT/node_modules/pm2/lib/VersionCheck.js:2:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/Adachi-BOT/node_modules/pm2/lib/VersionCheck.js',
    '/root/Adachi-BOT/node_modules/pm2/lib/Client.js',
    '/root/Adachi-BOT/node_modules/pm2/lib/API.js',
    '/root/Adachi-BOT/node_modules/pm2/lib/binaries/CLI.js',
    '/root/Adachi-BOT/node_modules/pm2/bin/pm2'
  ]
}
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@pm2/pm2-version-check'
Require stack:
- /root/Adachi-BOT/node_modules/pm2/lib/VersionCheck.js
- /root/Adachi-BOT/node_modules/pm2/lib/Client.js
- /root/Adachi-BOT/node_modules/pm2/lib/API.js
- /root/Adachi-BOT/node_modules/pm2/lib/binaries/CLI.js
- /root/Adachi-BOT/node_modules/pm2/bin/pm2
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/Adachi-BOT/node_modules/pm2/lib/VersionCheck.js:2:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/Adachi-BOT/node_modules/pm2/lib/VersionCheck.js',
    '/root/Adachi-BOT/node_modules/pm2/lib/Client.js',
    '/root/Adachi-BOT/node_modules/pm2/lib/API.js',
    '/root/Adachi-BOT/node_modules/pm2/lib/binaries/CLI.js',
    '/root/Adachi-BOT/node_modules/pm2/bin/pm2'
  ]
}

```

**Comment by Mark9804** [comment]
我想确认一下，你是在bot的根目录下执行的npm run start吗？
并且文件的读写、执行权限都给了吗？

**Comment by Nigel-NI** [comment]
谢谢回复，刚才我dd了一下系统，重新跑了一下npm install，发现有一部分内容好像没有顺利安装安装；配置了http代理后，bot正常运行并挂在后台。所以我认为，应该是国内服务器在执行npm install指令时发生了网络阻断导致部分内容无法顺利安装。在此向各位开发大大说声抱歉，有劳大家了！

**Comment by Mark9804** [comment]
@Arondight 要不要把这个issue也打一个documentation tag？

**Comment by Arondight** [comment]
@Nigel-NI 没事的，解决了就好

@Mark9804 没必要吧，不是很普适
