### ISSUE TITLE
关于 gacha/data.js 中出现的 undefine 报错

### ISSUE THREAD

**Issue by sunist-c** [Arondight/Adachi-BOT#496]
### 问题描述

在进行十连操作时，除了彩蛋卡池可以正常响应外，其他都会报此错误。

操作系统： macOS Monterey 12.0 Beta (21A5294g)
系统架构： Apple M1 (arm64)
Node版本： v16.6.2/v16.13.1(均会出现)
Npm版本： npm7.20.3/yarn 1.22.17(均会出现)

在gacha.js中添加了如下log语句：

```js
--- a/src/plugins/gacha/data.js
+++ b/src/plugins/gacha/data.js
@@ -119,6 +119,7 @@ function gachaOnceEggs() {
 }
 
 function gachaOnce(userID, choice, table) {
+  console.log(table);
   const star = getStar(userID, choice);
   const up = getIsUp(userID, star);
   const times = five;
@@ -180,6 +181,7 @@ function gachaOnce(userID, choice, table) {
     return { ...result, star: 4 };
   } else {
     // 没出货：三星
+    console.log(table)
     const index = getRandomInt(table.threeStar.length) - 1;
     result = table.threeStar[index];
     return { ...result, star: 3 };
@@ -190,6 +192,7 @@ function gachaTimes(userID, nickname, times = 10) {
   const { choice: uchoice } = db.get("gacha", "user", { userID }) || {};
   const choice = uchoice ? uchoice : 301;
   const gachaTable = db.get("gacha", "data", { gacha_type: choice }) || {};
+  console.log(gachaTable);
   let gachaResults = [];
   let data = {};
```

输出结果均为：

```txt
{}
```

### 复现流程

任何情况下都有此错误。

### 后台日志

```Text
TypeError: Cannot read properties of undefined (reading 'length')
    at gachaOnce (file:///Users/sunist/Projects/GitHub/Adachi-BOT/src/plugins/gacha/data.js:185:48)
    at gachaTimes (file:///Users/sunist/Projects/GitHub/Adachi-BOT/src/plugins/gacha/data.js:206:23)
    at doGacha (file:///Users/sunist/Projects/GitHub/Adachi-BOT/src/plugins/gacha/gacha.js:7:15)
    at Module.Plugin (file:///Users/sunist/Projects/GitHub/Adachi-BOT/src/plugins/gacha/index.js:21:9)
    at processedPossibleCommand (file:///Users/sunist/Projects/GitHub/Adachi-BOT/src/utils/load.js:167:27)
    at processed (file:///Users/sunist/Projects/GitHub/Adachi-BOT/src/utils/load.js:213:9)
    at Client.<anonymous> (file:///Users/sunist/Projects/GitHub/Adachi-BOT/app.js:140:40)
    at Client.emit (node:events:390:28)
    at Client.em (/Users/sunist/Projects/GitHub/Adachi-BOT/node_modules/oicq/lib/client-ext.js:146:14)
    at /Users/sunist/Projects/GitHub/Adachi-BOT/node_modules/oicq/lib/client-ext.js:293:38
TypeError: Cannot read properties of undefined (reading 'length')
    at gachaOnce (file:///Users/sunist/Projects/GitHub/Adachi-BOT/src/plugins/gacha/data.js:185:48)
    at gachaTimes (file:///Users/sunist/Projects/GitHub/Adachi-BOT/src/plugins/gacha/data.js:206:23)
    at doGacha (file:///Users/sunist/Projects/GitHub/Adachi-BOT/src/plugins/gacha/gacha.js:7:15)
    at Module.Plugin (file:///Users/sunist/Projects/GitHub/Adachi-BOT/src/plugins/gacha/index.js:21:9)
    at processedPossibleCommand (file:///Users/sunist/Projects/GitHub/Adachi-BOT/src/utils/load.js:167:27)
    at processed (file:///Users/sunist/Projects/GitHub/Adachi-BOT/src/utils/load.js:213:9)
    at Client.<anonymous> (file:///Users/sunist/Projects/GitHub/Adachi-BOT/app.js:140:40)
    at Client.emit (node:events:390:28)
    at Client.em (/Users/sunist/Projects/GitHub/Adachi-BOT/node_modules/oicq/lib/client-ext.js:146:14)
    at /Users/sunist/Projects/GitHub/Adachi-BOT/node_modules/oicq/lib/client-ext.js:293:38
```

### 代码状态：当前提交

4a62169d029b58d8e9c9791b1015e4153451687e (HEAD -> master, origin/master, origin/HEAD) 更新周本图片

### 代码状态：是否修改

Dirty

### 运行环境： Node.js 版本

v16.6.2

### 运行环境： npm 版本

7.20.3

### 运行环境：操作系统

macOS

**Comment by Arondight** [comment]
啊这，我这里没有任何错误啊，你直接拉一份最新的代码试一下？

**Comment by Arondight** [comment]
哦，我新拉了一个代码，有了

**Comment by Arondight** [comment]
怎么卡池的 api 还变了啊，拉不到池子信息了
