### ISSUE TITLE
指定卡池为彩蛋或常驻后抽卡时，bot报错

### ISSUE THREAD

**Issue by Nigel-NI** [Arondight/Adachi-BOT#653]
### 问题描述

抽卡时报错

### 复现流程

指定卡池为彩蛋或常驻后发送“抽卡”指令，bot无响应，后台报错，日志如下

### 后台日志

```Text
0|bot  | TypeError: Cannot read properties of undefined (reading '0')
0|bot  |     at gachaTimes (file:///root/Adachi-BOT/src/plugins/gacha/data.js:248:89)
0|bot  |     at doGacha (file:///root/Adachi-BOT/src/plugins/gacha/gacha.js:8:18)
0|bot  |     at Module.Plugin (file:///root/Adachi-BOT/src/plugins/gacha/index.js:22:9)
0|bot  |     at doPossibleCommand (file:///root/Adachi-BOT/src/utils/load.js:126:27)
0|bot  |     at processed (file:///root/Adachi-BOT/src/utils/load.js:193:9)
0|bot  |     at Client.<anonymous> (file:///root/Adachi-BOT/app.js:89:26)
0|bot  |     at Client.emit (node:events:390:28)
0|bot  |     at Client.em (/root/Adachi-BOT/node_modules/oicq/lib/client.js:519:18)
0|bot  |     at Client.groupMsgListener (/root/Adachi-BOT/node_modules/oicq/lib/internal/onlinepush.js:409:14)
0|bot  |     at Client.eventsListener (/root/Adachi-BOT/node_modules/oicq/lib/internal/listeners.js:81:41)
```
```


### 代码状态：当前提交

22bab9ca06501fe46eaf0f395bbf7ef14184f314 (HEAD -> master, origin/master, origin/dev, origin/HEAD) artifact: 2 → 3, Close #515, Close #412

### 代码状态：是否修改

_No response_

### 运行环境： Node.js 版本

_No response_

### 运行环境： npm 版本

_No response_

### 运行环境：操作系统

Linux

**Comment by Arondight** [comment]
Duplicate of #652
