### ISSUE TITLE
不能正确处理群转让消息

### ISSUE THREAD

**Issue by Mark9804** [Arondight/Adachi-BOT#666]
### 问题描述

```
0|bot  | [2022-02-22T14:54:23.098] [INFO] [iPad:2581109178] - 群31*****被转让给204****
0|bot  | [2022-02-22T14:54:23.099] [DEBUG] [iPad:2581109178] - TypeError: Cannot read properties of undefined (reading 'get')
0|bot  |     at Client.onlinePushTransListener (/Users/mark_chen/Documents/GitHub.nosync/adachi-bot-fork/node_modules/oicq/lib/internal/onlinepush.js:323:30)
0|bot  |     at Client.eventsListener (/Users/mark_chen/Documents/GitHub.nosync/adachi-bot-fork/node_modules/oicq/lib/internal/listeners.js:81:41)
0|bot  |     at Client.emit (node:events:538:35)
0|bot  |     at Client.packetListener (/Users/mark_chen/Documents/GitHub.nosync/adachi-bot-fork/node_modules/oicq/lib/core/base-client.js:634:18)
0|bot  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### 复现流程

--

### 后台日志

```Text
--
```

### 代码状态：当前提交

--

### 代码状态：是否修改

Clean

### 运行环境：操作系统

macOS

**Comment by Arondight** [comment]
Duplicate of https://github.com/takayama-lily/oicq/issues/310

**Comment by Arondight** [comment]
d4d73f0
