### ISSUE TITLE
信息文件中的 access 不统一

### ISSUE THREAD

**Issue by Arondight** [Arondight/Adachi-BOT#752]
### 问题描述

当前在代码里用不了

### 复现流程

111

### 运行环境

```Text
111
```

### 当前提交

```Text
qqq
```

### 代码状态

```Text
qqq
```

**Comment by Mark9804** [comment]
我记得都是限定祈愿吧，不过之前文件是手打的时候，确实还有一些不统一的问题。比如说卢姥爷神之眼写的火属性，其他人都是火元素，结果第一版 overview 字典没命中 fallback 到风属性上了，卢姥爷绿了一天

**Comment by Mark9804** [comment]
爬虫里的占位符可以改成限定祈愿

**Comment by Arondight** [comment]
> 爬虫里的占位符可以改成限定祈愿

确实，统一写成祈愿或者抽卡，现在乱七八糟的，我也没找到什么合适的地方去限定这个字符串

**Comment by Arondight** [comment]
1. 祈愿
2. NPC
3. 宝箱
4. 纪行
5. 特殊途径

**Comment by Arondight** [comment]
另外 cv 我也想改了，增加 cvCN 和 cvJP 顺手把网页也改了，现在的 cv 属性不要了

**Comment by Arondight** [comment]
> 现在的 cv 属性不要了

做个兼容留着吧

**Comment by Mark9804** [comment]
那既然老大哥掌握了 vue 的基本操作，前端改动就拜托了

https://github.com/Arondight/Adachi-BOT/blob/07be3484cc3e6bcb6f5aa4ab31d15ab377834dd2/src/views/component/overview/characterInfoBox.js#L118-L120

**Comment by Arondight** [comment]
> 那既然老大哥掌握了 vue 的基本操作，前端改动就拜托了
> 
> https://github.com/Arondight/Adachi-BOT/blob/07be3484cc3e6bcb6f5aa4ab31d15ab377834dd2/src/views/component/overview/characterInfoBox.js#L118-L120

完全OK

**Comment by Arondight** [comment]
> 1. 祈愿
> 
>     2. NPC
> 
>     3. 宝箱
> 
>     4. 纪行
> 
>     5. 特殊途径

这个东西写到文档里吧，实在是找不到什么地方给限定死了，只能当一个文本约定了

**Comment by Arondight** [comment]
我日，忘了跑爬虫了，下周一再说吧

**Comment by Arondight** [comment]
```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'textContent')
    at __puppeteer_evaluation_script__:1:11
    at ExecutionContext._evaluateInternal (F:\Repo\Arondight\Adachi-BOT\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (F:\Repo\Arondight\Adachi-BOT\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async getWeaponData (file:///F:/Repo/Arondight/Adachi-BOT/tools/info.js:474:19)
    at async getData (file:///F:/Repo/Arondight/Adachi-BOT/tools/info.js:540:16)
    at async main (file:///F:/Repo/Arondight/Adachi-BOT/tools/info.js:615:24)
```

- [ ] 试作斩岩
- [ ] 铁蜂刺
- [ ] 天目影打刀
