### ISSUE TITLE
Chormium 路径问题

### ISSUE THREAD

**Issue by BTMuli** [Arondight/Adachi-BOT#833]
### 问题描述

按照 README 修改 puppter 的步骤把自己安得 chromium 路径给加上了：
```sh
cp -v ~/.bashrc{,-backup}

echo 'export PUPPETEER_EXECUTABLE_PATH="/snap/bin/chromium"' | tee -a ~/.bashrc
echo 'export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"' | tee -a ~/.bashrc
source ~/.bashrc
```
跑 `npm run init`没问题，但跑 `npm run start`的时候报错，报的错跟没有加路径之前是一样的：
```sh
0|bot  | [2022-06-10T14:21:48.968] [DEBUG] [iPad:3628769149] - 正在从 /root/Adachi/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome 拉起浏览器实例。
0|bot  | file:///root/Adachi/node_modules/puppeteer/lib/esm/puppeteer/node/Launcher.js:78
0|bot  |                 throw new Error(missingText);
0|bot  |                       ^
0|bot  | Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1002410).
0|bot  |     at ChromeLauncher.launch (file:///root/Adachi/node_modules/puppeteer/lib/esm/puppeteer/node/Launcher.js:78:23)
0|bot  |     at async renderOpen (file:///root/Adachi/src/utils/render.js:47:22)
0|bot  |     at async initBrowser (file:///root/Adachi/src/bot/init.js:28:3)
0|bot  |     at async init (file:///root/Adachi/src/bot/init.js:104:3)
0|bot  |     at async main (file:///root/Adachi/bot.js:131:3)
0|bot  | app.js: 机器人异常退出！
0|bot  | app.js: 正在退出……
0|bot  | app.js: 正在终止文件服务器……
0|bot  | app.js: 正在终止机器人……
```
这两个指令调用的配置不一样吗？还是初始化的配置没有正确加载出来？
看了下输出，两个命令拉起浏览器实例的位置确实是不一样的。

### 复现流程

`npm run start`

### 后台日志

```Text
0|bot  | [2022-06-10T14:21:48.968] [DEBUG] [iPad:3628769149] - 正在从 /root/Adachi/node_modules/puppeteer/.local-chromium/linux-1002410/chrome-linux/chrome 拉起浏览器实例。
0|bot  | file:///root/Adachi/node_modules/puppeteer/lib/esm/puppeteer/node/Launcher.js:78
0|bot  |                 throw new Error(missingText);
0|bot  |                       ^
0|bot  | Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (1002410).
0|bot  |     at ChromeLauncher.launch (file:///root/Adachi/node_modules/puppeteer/lib/esm/puppeteer/node/Launcher.js:78:23)
0|bot  |     at async renderOpen (file:///root/Adachi/src/utils/render.js:47:22)
0|bot  |     at async initBrowser (file:///root/Adachi/src/bot/init.js:28:3)
0|bot  |     at async init (file:///root/Adachi/src/bot/init.js:104:3)
0|bot  |     at async main (file:///root/Adachi/bot.js:131:3)
0|bot  | app.js: 机器人异常退出！
0|bot  | app.js: 正在退出……
```

### 运行环境

```Text
操作系统：linux（Ubuntu）
内核版本：5.4.0-100-generic
内核架构：x64
处理器：  12.67%（Intel Xeon® Gold 6278C @ 2.6Ghz）
启动时间：2 hours
内存使用：15.00%（618 MB / 4.12 GB）
数据占用：1.16 MB
Node.js： 16.15.1
npm：     8.12.1
浏览器：  Chromium 102.0.5005.61 snap
```

### 当前提交

```Text
commit 0f7bae5ce56a4d752f888f4f279cc0f24bff4faa (HEAD -> luck, origin/luck)
Merge: e26bf02f 43243042
Author: BTMuli <72692909+BTMuli@users.noreply.github.com>
Date:   Tue Jun 7 18:04:38 2022 +0800

    Merge branch 'Arondight:master' into luck
```

### 代码状态

```Text
On branch luck
Your branch is up to date with 'origin/luck'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by Arondight** [comment]
没用过 snap ，检查一下该路径是不是 chrome 的二进制 elf

**Comment by Arondight** [comment]
删掉 bot.pm2 ，然后再 npm run start

**Comment by BTMuli** [comment]
能跑了，但是绘图报错`TimeoutError: Navigation timeout of 30000 ms exceeded`，服务器配置改了半天还是这样T_T
